TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
    ../soc_plasma/c_plasma/filtre/Sources/main.c \
    ../soc_plasma/c_plasma/mandelbrot/Sources/main.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/main.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/rayintersect.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/raylight.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/raymath.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/raymathfix.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/rayobject.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/rayplane.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/rayrender.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources/raysphere.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources_GL/glrenderer.c \
    ../soc_plasma/c_plasma/ray_tracer_v3/Sources_GL/text.c \
    ../soc_plasma/c_plasma/shared/no_os.c \
    ../soc_plasma/c_plasma/tools/bintohex.c \
    ../soc_plasma/c_plasma/tools/bootldr.c \
    ../soc_plasma/c_plasma/tools/convert.c \
    ../soc_plasma/c_plasma/tools/count.c \
    ../soc_plasma/c_plasma/tools/ddr_init.c \
    ../soc_plasma/c_plasma/tools/etermip.c \
    ../soc_plasma/c_plasma/tools/exec_generator.c \
    ../soc_plasma/c_plasma/tools/main.c \
    ../soc_plasma/c_plasma/tools/mlite.c \
    ../soc_plasma/c_plasma/tools/no_os.c \
    ../soc_plasma/c_plasma/tools/pi.c \
    ../soc_plasma/c_plasma/tools/ram_image.c \
    ../soc_plasma/c_plasma/tools/test.c \
    ../soc_plasma/c_plasma/tools/tracehex.c \
    ../soc_plasma/c_plasma/tuto_plasma/Sources/main.c \
    ../soc_plasma/c_plasma/tuto_plasma/ToTrash/main.c \
    ../soc_plasma/c_plasma/tuto_plasma/ToTrash/main33.c \
    ../soc_plasma/c_plasma/tuto_plasma/main_rgb.c \
    ../soc_plasma/synthese/IPBus_ml605_ASIP/firmware/ethernet/sim/modelsim_fli/mac_fli.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_hello/hello.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_hello/no_os.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_pcie/no_os.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_pcie/pcie.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_pcie_loop/no_os.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_pcie_loop/pcie_loop.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_sobel/no_os.c \
    ../soc_plasma/vhdl/plasma_core/apps/library_sobel/pcie.c \
    ../soc_plasma/vhdl/plasma_core/apps/bintohex.c \
    ../soc_plasma/vhdl/plasma_core/apps/bootldr.c \
    ../soc_plasma/vhdl/plasma_core/apps/convert.c \
    ../soc_plasma/vhdl/plasma_core/apps/count.c \
    ../soc_plasma/vhdl/plasma_core/apps/ddr_init.c \
    ../soc_plasma/vhdl/plasma_core/apps/etermip.c \
    ../soc_plasma/vhdl/plasma_core/apps/exec_generator.c \
    ../soc_plasma/vhdl/plasma_core/apps/main.c \
    ../soc_plasma/vhdl/plasma_core/apps/mlite.c \
    ../soc_plasma/vhdl/plasma_core/apps/no_os.c \
    ../soc_plasma/vhdl/plasma_core/apps/pi.c \
    ../soc_plasma/vhdl/plasma_core/apps/ram_image.c \
    ../soc_plasma/vhdl/plasma_core/apps/test.c \
    ../soc_plasma/vhdl/plasma_core/apps/tracehex.c \
    ../soc_plasma/vhdl/plasma_core/kernel/dlltest.c \
    ../soc_plasma/vhdl/plasma_core/kernel/ethernet.c \
    ../soc_plasma/vhdl/plasma_core/kernel/filesys.c \
    ../soc_plasma/vhdl/plasma_core/kernel/flash.c \
    ../soc_plasma/vhdl/plasma_core/kernel/http.c \
    ../soc_plasma/vhdl/plasma_core/kernel/libc.c \
    ../soc_plasma/vhdl/plasma_core/kernel/math.c \
    ../soc_plasma/vhdl/plasma_core/kernel/netutil.c \
    ../soc_plasma/vhdl/plasma_core/kernel/os_stubs.c \
    ../soc_plasma/vhdl/plasma_core/kernel/rtos.c \
    ../soc_plasma/vhdl/plasma_core/kernel/rtos_test.c \
    ../soc_plasma/vhdl/plasma_core/kernel/tcpip.c \
    ../soc_plasma/vhdl/plasma_core/kernel/uart.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/dlltest.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/ethernet.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/filesys.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/flash.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/http.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/libc.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/main.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/main_only.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/math.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/netutil.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/os_stubs.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/rtos.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/rtos_test.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/tcpip.c \
    ../soc_plasma/vhdl/plasma_core/nkernel/uart.c \
    ../soc_plasma/vhdl/plasma_core/tools/bench_hello/hello.c \
    ../soc_plasma/vhdl/plasma_core/tools/bench_hello/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_load/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_load/pcie.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_loader/ddr_test.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_loader/FileLoader.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_loader/LocalRamTester.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_loader/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_loader/ProgramExec.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_pcie/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_pcie/pcie.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_zeros/boot_zeros.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_zeros/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/boot_zeros/pcie_bench.c \
    ../soc_plasma/vhdl/plasma_core/tools/library_hello/hello.c \
    ../soc_plasma/vhdl/plasma_core/tools/library_hello/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/test_asip/main.c \
    ../soc_plasma/vhdl/plasma_core/tools/test_asip/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/bintohex.c \
    ../soc_plasma/vhdl/plasma_core/tools/bootldr.c \
    ../soc_plasma/vhdl/plasma_core/tools/convert.c \
    ../soc_plasma/vhdl/plasma_core/tools/count.c \
    ../soc_plasma/vhdl/plasma_core/tools/ddr_init.c \
    ../soc_plasma/vhdl/plasma_core/tools/etermip.c \
    ../soc_plasma/vhdl/plasma_core/tools/exec_generator.c \
    ../soc_plasma/vhdl/plasma_core/tools/main.c \
    ../soc_plasma/vhdl/plasma_core/tools/mlite.c \
    ../soc_plasma/vhdl/plasma_core/tools/no_os.c \
    ../soc_plasma/vhdl/plasma_core/tools/pi.c \
    ../soc_plasma/vhdl/plasma_core/tools/ram_image.c \
    ../soc_plasma/vhdl/plasma_core/tools/test.c \
    ../soc_plasma/vhdl/plasma_core/tools/tracehex.c

HEADERS += \
    ../soc_plasma/c_plasma/filtre/Includes/filtrage.h \
    ../soc_plasma/c_plasma/mandelbrot/Includes/converence.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/rayintersect.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/raylight.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/raymath.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/raymathfix.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/rayobject.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/rayplane.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/rayrender.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/raysphere.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes/raytypes.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes_GL/glrenderer.h \
    ../soc_plasma/c_plasma/ray_tracer_v3/Includes_GL/text.h \
    ../soc_plasma/c_plasma/shared/ToTrash/instructions.h \
    ../soc_plasma/c_plasma/shared/plasma.h \
    ../soc_plasma/c_plasma/shared/plasmaCoprocessors.h \
    ../soc_plasma/c_plasma/shared/plasmaFifoInOut.h \
    ../soc_plasma/c_plasma/shared/plasmaIsaCustom.h \
    ../soc_plasma/c_plasma/shared/plasmaMisc.h \
    ../soc_plasma/c_plasma/shared/plasmaMyPrint.h \
    ../soc_plasma/c_plasma/shared/plasmaSoPCDesign.h \
    ../soc_plasma/c_plasma/tools/plasma.h \
    ../soc_plasma/c_plasma/tuto_plasma/Includes/scale.h \
    ../soc_plasma/c_plasma/tuto_plasma/ToTrash/Coprocessors.h \
    ../soc_plasma/c_plasma/tuto_plasma/ToTrash/Isa_Custom.h \
    ../soc_plasma/c_plasma/tuto_plasma/ToTrash/SoPC_Design.h \
    ../soc_plasma/vhdl/plasma_core/apps/plasma.h \
    ../soc_plasma/vhdl/plasma_core/kernel/dll.h \
    ../soc_plasma/vhdl/plasma_core/kernel/rtos.h \
    ../soc_plasma/vhdl/plasma_core/kernel/tcpip.h \
    ../soc_plasma/vhdl/plasma_core/nkernel/dll.h \
    ../soc_plasma/vhdl/plasma_core/nkernel/rtos.h \
    ../soc_plasma/vhdl/plasma_core/nkernel/tcpip.h \
    ../soc_plasma/vhdl/plasma_core/tools/boot_load/instructions.h \
    ../soc_plasma/vhdl/plasma_core/tools/boot_zeros/instructions.h \
    ../soc_plasma/vhdl/plasma_core/tools/plasma.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/GRAPHLAB/SEQ_SUM_8d_8b_6c_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/GRAPHLAB/SEQ_SUM_8d_8b_6c_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_ABS_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_ABS_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_ADD_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_ADD_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_CondInv_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_CondInv_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_CondSelect_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_CondSelect_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_DECISION_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_DECISION_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_DoubleMini_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_DoubleMini_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_FullCondSelect_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_FullCondSelect_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_FullXorMin_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_FullXorMin_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_IndexLUT_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_IndexLUT_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_SIGN_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_SIGN_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_SUB_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q16_8_SUB_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q8_4_ABS_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q8_4_ABS_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q8_4_ADD_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q8_4_ADD_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q8_4_DECISION_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/Q8_4_DECISION_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/XOR_MIN_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/LDPC/XOR_MIN_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_ADD_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_ADD_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_EQU_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_EQU_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_GRT_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_GRT_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MAX_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MAX_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MIN_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MIN_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MIX_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MIX_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MUL_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_MUL_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_SUB_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_SUB_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_SUM_8b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/MMX/MMX_SUM_8b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/DIVIDER_2x_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/DIVIDER_2x_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/DIVIDER_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/DIVIDER_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/DIVIDER_AND_MODULUS_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/DIVIDER_AND_MODULUS_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MAXIMUM_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MAXIMUM_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MAXIMUM_MINIMUM_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MAXIMUM_MINIMUM_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MINIMUM_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MINIMUM_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MODULUS_2x_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MODULUS_2x_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MODULUS_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/MODULUS_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/PGDC_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/PGDC_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/REVERSE_BIT_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/REVERSE_BIT_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/REVERSE_BYTE_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/REVERSE_BYTE_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/RIGHT_SHIFTER_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/OTHERS/RIGHT_SHIFTER_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/UNDEF/START_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/UNDEF/START_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/UNDEF/STOP_32b_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/UNDEF/STOP_32b_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/video/LWT_FIR1_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/video/LWT_FIR1_TEST.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/video/RGB_2_YUV_DECL.h \
    ../soc_plasma/vhdl/plasma_core/vhdl/ims/to_trash/video/RGB_2_YUV_TEST.h
